[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/razonyang/hb-header"

[[module.imports]]
path = "github.com/razonyang/hb-footer"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons-bootstrap"

[params.hb.terms]
paginate = 9
